# SPDX-License-Identifier: GPL-3.0-or-later
"""Command-line interface for the read-only canonical two-chunk planner."""
from __future__ import annotations

import argparse
import csv
import sys
from dataclasses import asdict
from pathlib import Path

from two_chunk_planner.boundary_time import evaluate_surface_arc_heuristic
from two_chunk_planner.domain import CanonicalTwoChunkDomain
from two_chunk_planner.errors import PlannerError
from two_chunk_planner.io import Source, logical, number, parse_cmtsolution, parse_par_file, parse_station_csv, parse_stations, parse_target_region, parse_weights, write_json
from two_chunk_planner.optimize import SearchSettings, resource_suggestions, search
from two_chunk_planner.paths import geometry_paths, taup_paths
from two_chunk_planner.plotting import write_globe, write_map
from two_chunk_planner.profile import canonical_profile
from two_chunk_planner.transforms import EulerTransform


def _comma_list(value: str, cast=str) -> list:
    return [cast(item.strip()) for item in value.split(",") if item.strip()]


def _nex(value: str) -> tuple[int, int]:
    parts = value.lower().split("x")
    if len(parts) != 2:
        raise argparse.ArgumentTypeError("NEX candidate must be XIxETA, for example 96x96")
    return int(parts[0]), int(parts[1])


def _source(args) -> Source:
    if args.cmtsolution and args.source:
        raise PlannerError("choose CMTSOLUTION or --source, not both")
    if args.cmtsolution:
        return parse_cmtsolution(args.cmtsolution)
    if args.source:
        latitude, longitude, depth = args.source
        return Source(latitude, longitude, depth)
    raise PlannerError("CMTSOLUTION or --source LAT LON DEPTH is required")


def _stations(args):
    if bool(args.stations) == bool(args.stations_csv):
        raise PlannerError("provide exactly one of --stations or --stations-csv")
    return parse_stations(args.stations) if args.stations else parse_station_csv(args.stations_csv)


def _par_fragment(candidate, resources) -> str:
    lines = [
        "# Generated by two_chunk_planner: canonical planning suggestion only.",
        "# This is not a complete Par_file and does not verify your SPECFEM source.",
        "# Before a production simulation, separately apply and verify the accepted two-chunk patch.",
        "# This planner does not replace mesh, Stacey, boundary-return, or waveform acceptance.",
        "NCHUNKS                         = 2",
        "ANGULAR_WIDTH_XI_IN_DEGREES     = 90.d0",
        "ANGULAR_WIDTH_ETA_IN_DEGREES    = 90.d0",
    ]
    if candidate is None:
        return "\n".join(lines + ["# No feasible center/gamma candidate was found."]) + "\n"
    lines.extend([
        f"CENTER_LATITUDE_IN_DEGREES      = {candidate.center_latitude_deg:.8f}d0",
        f"CENTER_LONGITUDE_IN_DEGREES     = {candidate.center_longitude_deg:.8f}d0",
        f"GAMMA_ROTATION_AZIMUTH          = {candidate.gamma_rotation_azimuth_deg:.8f}d0",
    ])
    if resources:
        choice = resources[0]
        lines.extend([f"NEX_XI                          = {choice.nex_xi}", f"NEX_ETA                         = {choice.nex_eta}", f"NPROC_XI                        = {choice.nproc_xi}", f"NPROC_ETA                       = {choice.nproc_eta}", f"# total MPI ranks = {choice.total_ranks}; {choice.validation_status}"])
    return "\n".join(lines) + "\n"


def _write_csv(path: Path, candidates: list[dict]) -> None:
    fields = ["rank", "center_latitude_deg", "center_longitude_deg", "gamma_rotation_azimuth_deg", "feasible", "total_score", "rejection_reasons", "warnings"]
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        for index, item in enumerate(candidates, 1):
            row = {"rank": index, **{key: item.get(key) for key in fields if key not in {"rank", "rejection_reasons", "warnings"}}}
            row["rejection_reasons"] = "; ".join(item.get("rejection_reasons", []))
            row["warnings"] = "; ".join(item.get("warnings", []))
            writer.writerow(row)


def _planning_par(args, profile: dict) -> tuple[dict[str, str], str]:
    if args.par_file is None:
        return dict(profile["planning_defaults"]), "builtin_profile"
    return parse_par_file(args.par_file), "external_file"


def _resource_inputs(args, par: dict[str, str], profile: dict) -> tuple[list[tuple[int, int]], list[int]]:
    if args.nex:
        nex = args.nex
    elif "NEX_XI" in par and "NEX_ETA" in par:
        nex = [(int(number(par["NEX_XI"])), int(number(par["NEX_ETA"]))) ]
    else:
        defaults = profile["planning_defaults"]
        nex = [(int(defaults["NEX_XI"]), int(defaults["NEX_ETA"]))]
    if args.available_ranks is not None:
        ranks = args.available_ranks
    elif "NPROC_XI" in par and "NPROC_ETA" in par:
        ranks = [2 * int(number(par["NPROC_XI"])) * int(number(par["NPROC_ETA"]))]
    else:
        ranks = list(profile["resource_validation"]["project_validated_total_ranks"])
    return nex, ranks


def _verification(profile: dict, par_file_source: str) -> dict:
    warning = (
        "No user SPECFEM source or accepted patch was verified. Apply and verify the accepted two-chunk patch "
        "separately before a production simulation."
    )
    return {
        "planner_mode": profile["planner_mode"],
        "compatibility_profile_version": profile["profile_version"],
        "specfem_source_verified": False,
        "accepted_patch_verified": False,
        "production_configuration_verified": False,
        "par_file_source": par_file_source,
        "configuration_status": "external_par_file_read" if par_file_source == "external_file" else "planning_defaults_only",
        "verification_warnings": [warning],
    }


def run_plan(args) -> None:
    if args.output.exists():
        raise PlannerError(f"refusing to overwrite existing output directory: {args.output}")
    if not args.phases and args.analysis_window is None and args.target_energy_end_s is None:
        raise PlannerError("provide phases, analysis window, or target energy end time")
    if any(len(value) != 2 for value in (args.latitude_range, args.longitude_range, args.gamma_range)):
        raise PlannerError("each search range must be MIN,MAX")
    if not 0.0 < args.minimum_path_coverage <= 1.0:
        raise PlannerError("minimum path coverage must be in (0, 1]")
    if args.boundary_speed_upper_km_s is not None and args.boundary_speed_upper_km_s <= 0.0:
        raise PlannerError("boundary speed upper bound must be positive")
    profile = canonical_profile()
    source, stations = _source(args), _stations(args)
    par, par_file_source = _planning_par(args, profile)
    verification = _verification(profile, par_file_source)
    ellipticity = logical(par.get("ELLIPTICITY", ".false."))
    target = parse_target_region(args.target_region) if args.target_region else None
    weights = parse_weights(args.weights) if args.weights else None
    phases = _comma_list(args.phases) if args.phases else []
    phase_missing: list[dict] = []
    if args.path_mode == "phase-aware":
        paths, phase_missing = taup_paths(
            source, stations, phases, args.taup_model, args.taup_resample,
            args.ray_param_tol, args.allow_partial_phase_coverage,
            args.cmb_near_depth_tolerance_km,
        )
    else:
        paths = geometry_paths(source, stations, args.path_samples)
    phase_inventory = {
        "mode": "partial" if args.allow_partial_phase_coverage else "strict",
        "requested_pairs": [{"station_id": station.identifier, "requested_phase": phase} for station in stations for phase in phases],
        "provided_pairs": [{"station_id": item.station_id, "requested_phase": item.requested_phase, "returned_phase": item.returned_phase} for item in paths if item.mode == "phase-aware"],
        "missing_pairs": phase_missing,
    }
    if phase_missing:
        phase_inventory["warning"] = "partial phase coverage: unavailable requested phase-station pairs were not substituted"
    settings = SearchSettings(
        latitude_min=args.latitude_range[0], latitude_max=args.latitude_range[1], longitude_min=args.longitude_range[0], longitude_max=args.longitude_range[1], gamma_min=args.gamma_range[0], gamma_max=args.gamma_range[1],
        coarse_latitude_step=args.coarse_latitude_step, coarse_longitude_step=args.coarse_longitude_step, coarse_gamma_step=args.coarse_gamma_step,
        local_latitude_step=args.local_latitude_step, local_longitude_step=args.local_longitude_step, local_gamma_step=args.local_gamma_step,
        final_latitude_step=args.final_latitude_step, final_longitude_step=args.final_longitude_step, final_gamma_step=args.final_gamma_step,
    )
    result = search(source, stations, paths, target, ellipticity, args.minimum_path_coverage, settings, weights)
    nex, available_ranks = _resource_inputs(args, par, profile)
    resources = resource_suggestions(nex, available_ranks, par, profile["resource_validation"])
    if args.max_compute_cost is not None:
        resources = [item for item in resources if item.relative_lateral_work_per_rank <= args.max_compute_cost]
    candidate_dicts = [candidate.to_dict() | {"resource_suggestions": [item.to_dict() for item in resources]} for candidate in result.candidates]
    chosen = result.candidates[0] if result.candidates else None
    chosen_domain = CanonicalTwoChunkDomain(EulerTransform(chosen.center_latitude_deg, chosen.center_longitude_deg, chosen.gamma_rotation_azimuth_deg, ellipticity)) if chosen else CanonicalTwoChunkDomain(EulerTransform(0.0, 0.0, 0.0, ellipticity))
    boundary = evaluate_surface_arc_heuristic(chosen_domain, source, stations, args.boundary_speed_upper_km_s) if chosen else []
    analysis_end_s = args.target_energy_end_s if args.target_energy_end_s is not None else (args.analysis_window[1] if args.analysis_window else None)
    boundary_records = []
    for item in boundary:
        record = item.to_dict()
        record["analysis_end_s"] = analysis_end_s
        record["heuristic_margin_to_analysis_end_s"] = None if record["heuristic_earliest_return_s"] is None or analysis_end_s is None else record["heuristic_earliest_return_s"] - analysis_end_s
        record["comparison_status"] = "advisory_only" if analysis_end_s is not None else "analysis_end_unavailable"
        boundary_records.append(record)
    args.output.mkdir(parents=True)
    common = {**verification, "canonical_profile": profile["canonical_geometry"]}
    write_json(args.output / "candidates.json", {"schema": "ulvz_two_chunk_planner_candidates.v1", **common, "returned_candidate_count": len(candidate_dicts), "maximum_requested": 5, "search": {"generated_candidate_count": result.all_candidate_count, "deduplicated_candidate_count": result.deduplicated_candidate_count, "evaluated_count": result.evaluated_count, "feasible_count": result.feasible_count, "rejected_count": result.rejected_count, "rejection_summary": result.rejection_summary}, "phase_inventory": phase_inventory, "phase_paths": [item.to_dict() for item in paths], "candidates": candidate_dicts})
    _write_csv(args.output / "candidates.csv", candidate_dicts)
    (args.output / "recommended_Par_file.inc").write_text(_par_fragment(chosen, resources), encoding="utf-8")
    write_json(args.output / "geometry_audit.json", {**common, "ellipticity": ellipticity, "chosen_candidate": chosen.to_dict() if chosen else None, "phase_inventory": phase_inventory, "phase_paths": [item.to_dict() for item in paths]})
    write_json(args.output / "boundary_time_audit.json", {**common, "analysis_window": args.analysis_window, "target_energy_end_s": args.target_energy_end_s, "analysis_end_s": analysis_end_s, "records": boundary_records, "global_status": "heuristic_not_conservative" if boundary else "unavailable", "hard_constraint_used": False, "boundary_time_production_safe": False, "taup_path_use": "forbidden"})
    write_json(args.output / "run_manifest.json", {"schema": "ulvz_two_chunk_planner_run.v1", **verification, "canonical_profile": profile, "source": asdict(source), "stations": [asdict(item) for item in stations], "path_mode": args.path_mode, "taup_model": args.taup_model if args.path_mode == "phase-aware" else None, "taup_resample": args.taup_resample if args.path_mode == "phase-aware" else None, "ray_param_tol": args.ray_param_tol if args.path_mode == "phase-aware" else None, "cmb_near_depth_tolerance_km": args.cmb_near_depth_tolerance_km if args.path_mode == "phase-aware" else None, "phase_inventory": phase_inventory, "weights": weights, "large_simulation_run": False, "formal_source_modified": False, "formal_build_rules_modified": False, "accepted_patch_modified": False, "commit_performed": False, "push_performed": False})
    write_map(args.output / "map.png", chosen_domain, source, stations, paths, target)
    write_globe(args.output / "globe.png", chosen_domain, source, stations, paths, target)
    report = ["# Canonical two-chunk planning result", "", f"Returned feasible candidates: **{len(candidate_dicts)}** (maximum 5).", "", "## Scope", "", "This is a standalone, read-only canonical 90°×90° planner. It does not run mesher/database/solver and does not replace topology, Stacey, waveform, or production boundary-return validation.", "", "## Verification status", "", f"- planner mode: `{verification['planner_mode']}`", f"- compatibility profile: `{verification['compatibility_profile_version']}`", f"- Par_file source: `{verification['par_file_source']}`", "- SPECFEM source and accepted patch: **not verified by this planner**.", "", "## Search", "", f"Generated: {result.all_candidate_count}; deduplicated: {result.deduplicated_candidate_count}; feasible: {result.feasible_count}; rejected: {result.rejected_count}."]
    if not candidate_dicts:
        report.extend(["", "## No feasible candidate", "", *[f"- {reason}: {count}" for reason, count in result.rejection_summary.items()]])
    else:
        report.extend(["", "## Recommendation", "", f"- center: {chosen.center_latitude_deg:.6f}°, {chosen.center_longitude_deg:.6f}°", f"- gamma: {chosen.gamma_rotation_azimuth_deg:.6f}°", f"- score: {chosen.total_score:.6f}"])
    if args.path_mode == "phase-aware":
        report.extend(["", "## Phase inventory", "", f"- requested pairs: {len(phase_inventory['requested_pairs'])}", f"- provided geographic TauP paths: {len(phase_inventory['provided_pairs'])}", f"- missing pairs: {len(phase_inventory['missing_pairs'])}"])
        if phase_missing:
            report.append("- warning: partial coverage retained only returned requested phases; no phase substitution occurred.")
    report.extend(["", "## Boundary time", "", "Any reported seconds are `heuristic_not_conservative` surface-arc proxies and are advisory only. TauP phase paths are not used for boundary reflection timing."])
    (args.output / "report.md").write_text("\n".join(report) + "\n", encoding="utf-8")


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="two_chunk_planner", description="Read-only planner for the accepted canonical SPECFEM two-chunk geometry.")
    commands = parser.add_subparsers(dest="command", required=True)
    plan = commands.add_parser("plan", help="search center/gamma candidates and write audit reports")
    plan.add_argument("--cmtsolution", type=Path)
    plan.add_argument("--source", nargs=3, type=float, metavar=("LAT", "LON", "DEPTH_KM"))
    plan.add_argument("--stations", type=Path)
    plan.add_argument("--stations-csv", type=Path)
    plan.add_argument("--phases", help="comma-separated TauP phase names")
    plan.add_argument("--analysis-window", nargs=2, type=float, metavar=("START_S", "END_S"))
    plan.add_argument("--target-energy-end-s", type=float)
    plan.add_argument("--target-region", type=Path)
    plan.add_argument("--weights", type=Path, help="strict YAML mapping of coverage/external_margin/endpoint_margin/cost weights")
    plan.add_argument("--path-mode", choices=("geometry-only", "phase-aware"), default="geometry-only")
    plan.add_argument("--path-samples", type=int, default=121)
    plan.add_argument("--taup-model", default="prem")
    plan.add_argument("--taup-resample", action="store_true")
    plan.add_argument("--ray-param-tol", type=float, default=1.0e-6)
    plan.add_argument("--cmb-near-depth-tolerance-km", type=float, default=25.0)
    plan.add_argument("--allow-partial-phase-coverage", action="store_true")
    plan.add_argument("--boundary-speed-upper-km-s", type=float)
    plan.add_argument("--minimum-path-coverage", type=float, default=1.0)
    plan.add_argument("--available-ranks", type=lambda value: _comma_list(value, int), help="comma-separated total MPI-rank candidates; default uses external Par_file NPROC or profile 2,8,12")
    plan.add_argument("--nex", type=_nex, action="append")
    plan.add_argument("--max-compute-cost", type=float)
    plan.add_argument("--latitude-range", type=lambda value: _comma_list(value, float), default=[-90.0, 90.0])
    plan.add_argument("--longitude-range", type=lambda value: _comma_list(value, float), default=[-180.0, 180.0])
    plan.add_argument("--gamma-range", type=lambda value: _comma_list(value, float), default=[0.0, 360.0])
    for name, default in (("coarse-latitude-step", 10.0), ("coarse-longitude-step", 10.0), ("coarse-gamma-step", 15.0), ("local-latitude-step", 2.0), ("local-longitude-step", 2.0), ("local-gamma-step", 3.0), ("final-latitude-step", 0.5), ("final-longitude-step", 0.5), ("final-gamma-step", 0.5)):
        plan.add_argument(f"--{name}", type=float, default=default)
    plan.add_argument("--par-file", type=Path, help="optional arbitrary Par_file read only for resource compatibility; no SPECFEM source is verified")
    plan.add_argument("--output", type=Path, required=True)
    plan.set_defaults(func=run_plan)
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    try:
        args.func(args)
    except (PlannerError, FileNotFoundError, OSError, ValueError) as exc:
        print(f"two_chunk_planner: {exc}", file=sys.stderr)
        return 2
    return 0
